---

- hosts: default

  roles:
    - { role: tools, tags: ['tools']}
    - { role: authorized-key, tags: ['authorized-key']}
    - { role: instructor-user, tags: ['instructor-user']}

  tasks:

    - name: unsubscribe system
      redhat_subscription: state=absent

...
