---

- name: replace ec2-user with cloud-user
  replace:
    path: /etc/cloud/cloud.cfg
    regexp: 'ec2-user'
    replace: 'cloud-user'

- name: copy cfn-signal script
  copy:
    src: cfn-signal.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
